[package]
name = "haproxy"
version = "0.1.0"
edition = "2024"
authors = ["thochra"]
description = "HAProxy configuration syntax support for Zed"
repository = "https://github.com/thochra/zed-haproxy-extension"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
